apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: broker2
  name: broker2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: broker2
    spec:
      containers:
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: BROKER_ID
              value: "2"
            - name: JMX_PORT
              value: "10000"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://broker2:9093,EXTERNAL_SAME_HOST://localhost:29093
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_LISTENERS
              value: EXTERNAL_SAME_HOST://:29093,INTERNAL://:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
            - name: KAFKA_PORT
              value: "9093"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: bitnami/kafka
          name: broker2
          ports:
            - containerPort: 29093
          resources: {}
      hostname: broker2
      restartPolicy: Always
status: {}
