apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: command-service
  name: command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: command-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: command-service
    spec:
      containers:
        - image: command-service
          name: equip-cmd-svc
          ports:
            - containerPort: 80
          resources: {}
      hostname: equip-cmd-svc
      restartPolicy: Always
status: {}
