apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: event-listener
  name: event-listener
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: event-listener
status:
  loadBalancer: {}
