apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-ui
    spec:
      containers:
        - env:
            - name: JVM_OPTS
              value: -Xms32M -Xmx64M
            - name: KAFKA_BROKERCONNECT
              value: broker1:9092
          image: obsidiandynamics/kafdrop
          name: kafka-ui
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
