apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: query-service-db
  name: query-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: query-service-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: query-service-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Izz@2020@dmin"
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: equip-event-db
          ports:
            - containerPort: 1433
          resources: {}
      hostname: equip-event-db
      restartPolicy: Always
status: {}
